services:
  web:
    build: .
    ports:
      - '3000:3000'
    volumes:
      - .:/app
    environment:
      NODE_ENV: development
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    depends_on:
      - migrate

  db:
    image: postgres:14
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    ports:
      - '5433:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data

  migrate:
    build: .
    command: sh -c "npm run reset-db && npm run migrate && npm run seed"
    environment:
      NODE_ENV: development
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    depends_on:
      - db

volumes:
  postgres-data:
